name = "web3lite" # todo
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

[vars]
WORKERS_RS_VERSION = "0.0.12"
PHANTOM_ENCRYPTION_PUBLIC_KEY = "Bigf1Q8vseNX5TAGZpKkuoC51HMMmhZZCWrVBwy7R8kP"

[build]
command = "cargo install -q worker-build && worker-build --release"
